version: '2.2'
services:
  es01:
    image: elasticsearch:7.17.4
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: elasticsearch:7.17.4
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: elasticsearch:7.17.4
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data03:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana:7.17.4
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://es01:9200
    ports:
      - "5601:5601"
    networks:
      - elastic
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.17.4
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/software/tomcat-vehicle-archive/logs:/var/logs/vehicle-archive:ro
      - /usr/local/software/tomcat-driver-archive/logs:/var/logs/driver-archive:ro
      - /usr/local/software/tomcat-transpcorp-archive/logs:/var/logs/transpcorp-archive:ro
      - /usr/local/software/tomcat-event-archive/logs:/var/logs/event-archive:ro
      - /var/logs/traffic-cockpit:/var/logs/traffic-cockpit:ro
    networks:
      - elastic

volumes:
  es_data01:
    driver: local
  es_data02:
    driver: local
  es_data03:
    driver: local

networks:
  elastic:
    driver: bridge
